### ISSUE TITLE
Should we support subset arguments?

### ISSUE THREAD

**Issue by r-medicine** [swang87/fc#11]
The following doesn't currently have an `fc` equivalent:
```
subset(iris, Sepal.Length > 1)
```
Should it?

I don't think so. I just want to make sure.

**Comment by swang87** [comment]
Well, this works:
`fc(subset, subset=Sepal.Length > 1)(iris)`

Should it?

**Comment by kaneplusplus** [comment]
Hmm. Good point. In fact it'll work with any named argument starting with "subset"

```
fc(subset, subset123=Sepal.Length > 1)(iris)
```

It would work without naming the argument but fc requires a named argument so we know exactly which formal to map to in the passed function.
